In [57]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [58]:
env=gym.make("FrozenLake-v1", render_mode="ansi")

In [59]:
action_space_size= env.action_space.n
state_space_size= env.observation_space.n
q_table= np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [60]:
num_episodes=10000
max_steps_per_episode=100

learning_rate=0.1
discount_rate=0.99

exploration_rate=1
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.01


In [61]:
for episode in range(3):
    state=env.reset()
    done=False
    print("*****Episode ", episode+1, "****\n\n\n\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        print(env.render())

        time.sleep(0.3)
       
        action=np.argmax(q_table[state[0],:])
        
        var=env.step(action)
       
        new_state=[var[0],var[len(var)-1]]
        reward=var[1]
        done=var[2]
        info=var[3]
        
        if done :
            clear_output(wait=True)
            print(env.render())

            if reward==1:
                print("*****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
            clear_output(wait=True)
            break
        state=new_state
env.close()

  (Left)
SFFF
FHFH
FFFH
HFFG

****You fell through a hole!****
